### ISSUE TITLE
Can not compile on Linux

### ISSUE THREAD

**Issue by HuQingyang** [DualSPHysics/DualSPHysics#1]
Hey, this project is super awesome ! And I am going to use it on my graduation project. But when I tried to recompile DualSPHysics (the cpu version) on Linux (Ubuntu 16.04 LTS) using g++ (version 7.1.0), and I got some errors, I tried both this version and the official webpage.

![Error](https://user-images.githubusercontent.com/23466520/33919808-a33dfa4c-dff5-11e7-8e02-d402a66629de.png)

This is the full log: [Error Log](https://drive.google.com/open?id=1o-A3aLJ8iYQOgMnP5gOwYx969hW18pIn)

How can I make it works ? Thanks !

**Comment by ndrs92** [comment]
Hi again, 

I tried to compile in my system with GCC/G++ version 4.9 and it went fine. I leave you the details and I'll improve the documentation to make clear that it is indeed needed.

Basically I compiled it with `make CC=g++-4.9 CPP=g++-4.9 CXX=g++-4.9 LD=g++-4.9 -f ./Makefile_cpu`

Please let me know if it works for you to mark this as solved. For now I'm going to put it in the readme and wiki.

**Comment by HuQingyang** [comment]
I compiled it success using gcc-4.7 on Ubuntu 16.04!

Just run `sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
Then `sudo apt-get update` and `sudo apt-get install g++-4.9`
Finally complie with `make CC=g++-4.9 CPP=g++-4.9 CXX=g++-4.9 LD=g++-4.9 -f ./Makefile_cpu`

😉 SO MUCH THANKS !

**Comment by ndrs92** [comment]
Nice! I'm glad it worked.

I've put it in the README and in the wiki. I'm not including the repository information or distro information because of the tendency of change of that.

Closing this as it is currently resolved. Thanks for noticing the problem!
