### ISSUE TITLE
JWaveGen and JFormatFiles2 lib for VS2017

### ISSUE THREAD

**Issue by biqilong** [DualSPHysics/DualSPHysics#10]
Hi guys,

Could you provide the .lib files of JWaveGen and JFormatFiles2 for the vs 2017?

I'm recently using vs 2017 in windows 10 for building the code and I couldn't have these two libs for compilation.

Thanks in advance!

**Comment by jmdalonso** [comment]
It is possible to use libraries of vs2015 on vs2017. Anyway, the libraries for vs2017 were added in the branch "develop".
