### ISSUE TITLE
Chrono examples - corrupted size vs. prev_size

### ISSUE THREAD

**Issue by bcharbonneaupoly** [DualSPHysics/DualSPHysics#106]
Hi.

I compiled DualPhysic from sources on Oracle Linux 8.5.
G++: g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4.0.2).  

Makefile option:
USE_GCC5=YES
USE_DEBUG=NO
USE_FAST_MATH=YES
USE_NATIVE_CPU_OPTIMIZATIONS=NO
COMPILE_VTKLIB=YES
COMPILE_NUMEXLIB=YES
COMPILE_CHRONO=YES
COMPILE_WAVEGEN=YES
COMPILE_MOORDYN=YES

Compilation with "make -f Makefile_cpu"

Running the Chrono examples does not work.  Here is the output.  Thank you for your help!

[root@linux.xxxxxx]/opt/DualSPHysics_v5.0/examples/chrono/02_Spring >./xCaseBungieJump_linux64_CPU.sh
DualSPHysics5 v5.0.193 (23-07-2021)
====================================
LoadDsphConfig> .../bin/linux/DsphConfig.xml
Threads by host for parallel execution: 6

[Initialising JSphCpuSingle  17-03-2022 17:29:23]
ProgramFile=".../bin/linux/DualSPHysics5.0CPU_linux64"
ExecutionDir=".../examples/chrono/02_Spring"
XmlFile=".../02_Spring/CaseBungieJump_out/CaseBungieJump.xml"
OutputDir=".../chrono/02_Spring/CaseBungieJump_out"
OutputDataDir=".../02_Spring/CaseBungieJump_out/data"
XML-App: GenCase v5.0.238 (22-07-2021)
XML-Vars (uservars + ctes): CaseName=["CaseBungieJump"]  Data2D=[0]  Data2DPosy=[0]  H=[0.129904]  KernelSize=[0.259808]  B=[228571]  Gamma=[7]  Rhop0=[1000]  Dp=[0.05]  Gravity_x=[0]  Gravity_y=[0]  Gravity_z=[-9.81]  MassFluid=[0.125]  MassBound=[0.125]
XML-Vars (parameters): TimeMax=[10]  TimeOut=[0.01]
Threads by host for parallel execution in Chrono: 1
corrupted size vs. prev_size
./xCaseBungieJump_linux64_CPU.sh : ligne 59 : 1185190 Abandon                 (core dumped)${dualsphysicscpu} ${dirout}/${name} ${dirout} -dirdataout data -svres
Execution aborted.
Press any key to continue...

**Comment by imestevez** [comment]
This issue was fixed in the latest commit https://github.com/DualSPHysics/DualSPHysics/commit/5bc27f027de9f386b612815545403a081ca77ea8
