### ISSUE TITLE
Core restriction

### ISSUE THREAD

**Issue by benpietras** [DualSPHysics/DualSPHysics#107]
Hi,

I'm a sysadmin on a SGE HPC facility where a user is running DualSPHysics (local install).

He reserves 2 cores
#$ -pe smp.pe 2 
yet his job attempts **25**

PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                
224365 redacted  20   0  491148 324384   1864 R  **2543**  0.2   7384:42 PartVTK_linux64    

Do you have any advice regarding core restriction?

Cheers!

**Comment by jmdalonso** [comment]
Hi,

You can use the following execution parameter: -ompthreads:2
More information is available in the program's help using -h

Best regards
