### ISSUE TITLE
DSPHChronoLib.h:110:3: error: ‘FeaBeams’ does not name a type

### ISSUE THREAD

**Issue by kmktu** [DualSPHysics/DualSPHysics#108]
I used to Wsl Ubuntu build to DualSPHysics.
Build using MAKEFILE.

But I have build problem.

error code
- DSPHChronoLib.h:110:3: error: ‘FeaBeams’ does not name a type

![image](https://user-images.githubusercontent.com/42626963/163293096-6b71a10b-9564-47d9-87c9-7d12742318e1.png)

The build environment is as follows.

- WSL2
- Ubuntu 18.04
- CUDA 11.2
- gcc 7.5.0
- VS2015

Do you have any idea?

Thanks.

**Comment by imestevez** [comment]
Hello, we wil fix this issue in the next update. 
In the meantime, if you are not using Chrono, you can comment out that line in the DSPHChronoLib.h;  uncomment the line 51 (#define DISABLE_CHRONO) in the file DualSphDef.h; and recompile de code

**Comment by zweihuehner** [comment]
Is there also a workaround if one needs Chrono?

**Comment by kmktu** [comment]
Thanks you for answering But I need Chrono.... Is there any other way?

**Comment by imestevez** [comment]
This issue was fixed in the latest commit https://github.com/DualSPHysics/DualSPHysics/commit/5bc27f027de9f386b612815545403a081ca77ea8
