### ISSUE TITLE
JSphGpu_InOut_iker.cu(433): error: identifier "CODE_TYPE_FLUID_INOUT015MASK" is undefined

### ISSUE THREAD

**Issue by Nadun19** [DualSPHysics/DualSPHysics#126]
I am trying to compile a special version of DualSPHysis with CODE_SIZE4 set to true, and I am receiving this error. I believe this is because in DualSphDef.h when CODE_SIZE4 is set to true CODE_TYPE_FLUID_INOUT015MASK is not defined. Therefore, there is an error with the compilation of JSphGpu_InOut_iker.cu.

**Comment by imestevez** [comment]
This issue is fixed in the latest version of the code 8ad979c
