### ISSUE TITLE
Define Inter-Particle Distance in xml file

### ISSUE THREAD

**Issue by cyrildelaporte** [DualSPHysics/DualSPHysics#137]
Hi there, I'm new here and I am aware this is probably a very basic question. Sorry for that.

I want to run one of the example cases using the Batch file but with less particles. In the FreeCAD interface we can adjust the Inter-Particle distance easily in the Configuration prompt.  I am looking for a similar setting in the ```XXX_Def.xml``` file but I cant seem to find it.  Am I looking in the wrong place or did I overlook it? 

If anyone can help me figure this out, that would be great!

**Comment by imestevez** [comment]
Hello, you can define the inter-particle distance using the option  `<definition dp="0.1" comment="Initial inter-particle distance" units_comment="metres (m)">` included in the `XXX_Def.xml` file

**Comment by cyrildelaporte** [comment]
Off course, the comment was missing, i added it for clarity. Thank you!
