### ISSUE TITLE
mDBC geometry

### ISSUE THREAD

**Issue by Zahramht** [DualSPHysics/DualSPHysics#156]
Hello Everyone
I need to simulate my case in mDBC and I have simulated the ready examples with dambreak and wacecylinder but now I want to modify it for my case. but the way of coding these two examples is different. Could someone explain to me how I can modify it? 
P.S: I have read the 6th dualsphysics workshop about mDBC but still can't relate it with existing DEF files.
I would appreciate it in advance.
Regards

**Comment by imestevez** [comment]
Hello,

There are two methods to generate normals for mDBC: 

1.  Automatic normal vectors from actual geometry. This method is used in `04_CaseDambreak`, where the normal vectors are created from the geometry defined in section `<list name="GeometryForNormals">`. So you have to define the geometry of the objects manually and indicate, in section `<normals>`, the file that contains the geometry (generally `[CaseName]_hdp_Actual.vtk`).
2. Explicit normal vectors definition. This method is used in `07_WavesCylinder`, where you can see that the normals are created by defining the section `<initialize>...<boundnormal_cylinder mkbound="0">...</initialize>`. Thus, the normal vectors are created for the cylinder with mkbound="0" directly in this case.

Note that both methods can be combined and used in the same case. You can find more information in the pdf `doc/guides/XML_GUIDE_MDBC.pdf` and the available options for method 2 in `doc/xml_format/_FmtXML_Initialize.xml`

**Comment by Zahramht** [comment]
> Hello,
> 
> There are two methods to generate normals for mDBC:
> 
> 1. Automatic normal vectors from actual geometry. This method is used in `04_CaseDambreak`, where the normal vectors are created from the geometry defined in section `<list name="GeometryForNormals">`. So you have to define the geometry of the objects manually and indicate, in section `<normals>`, the file that contains the geometry (generally `[CaseName]_hdp_Actual.vtk`).
> 2. Explicit normal vectors definition. This method is used in `07_WavesCylinder`, where you can see that the normals are created by defining the section `<initialize>...<boundnormal_cylinder mkbound="0">...</initialize>`. Thus, the normal vectors are created for the cylinder with mkbound="0" directly in this case.
> 
> Note that both methods can be combined and used in the same case. You can find more information in the pdf `doc/guides/XML_GUIDE_MDBC.pdf` and the available options for method 2 in `doc/xml_format/_FmtXML_Initialize.xml`
Hello again 
Thank you for your prompt answer. 
I have been working on DBC so far and there were many tutorials about how should I define and modify different cases or even working with FreeCAD or XML files. 
Now in my case, What do you recommend? I am really confused with the XML file of the case wave cylinder with mDBC. Generally, I just want to modify that example by changing the cylinder with a simple vertical seawall and modifying the domain. But I don't know how can I do that and where to start.

**Comment by imestevez** [comment]
You can use the 1st method. 
To understand this method you can consider the example `mdbc/04_Dambreak`.

1. You define the geometry of the seawall in the `<mainlist>`.  With `drawbox` you create the shape (mkbound="0") and the option `<layers vdp="0,1,2" />` indicates where particles are created; in this case at 0, 1 and 2 dp from the shape definition.
```
  <setmkbound mk="0" />
  <!-- Left side of the tank -->
  <drawbox>
    <boxfill>all^top^right</boxfill>
    <point x="#Tankpx1" y="#Tankpy1" z="#Tankpz1" />
    <endpoint x="#Boxpx1" y="#Tankpy2" z="#Tankpz2" />
    <layers vdp="0,1,2" />
  </drawbox>
```

2. In  `<list name="GeometryForNormals">` , you have to indicate that you want only shapes:
  `<setactive drawpoints="0" drawshapes="1"/>`

4.  Add the geometry in the `<list name="GeometryForNormals">` to indicate where the boundary interface of mDBC is generated. So for this step, the same object (mkbound="0") has the same definition of the step 1), but in this case you indicate `<layers vdp="-0.5" />`, that means that the boundary interface is generated at -0.5 dp from the first layer of particles. Note that operation of `layers` could be different deppending on the `draw*` option you use, check the guide **XML_GUIDE_v5.2.pdf**.
```
  <setmkbound mk="0" />
  <setnormalinvert invert="true" />
  <!-- Left side of the tank -->
  <drawbox>
      <boxfill>all^top^right</boxfill>
      <point x="#Tankpx1" y="#Tankpy1" z="#Tankpz1" />
      <endpoint x="#Boxpx1-Dpm" y="#Tankpy2" z="#Tankpz2" />
      <layers vdp="-0.5" />
  </drawbox>
```

5. In section `<list name="GeometryForNormals">` you have to indicate the type of files created; keep `actual` by default for all the cases with method 1:
  `<setshapemode>actual | bound</setshapemode>`

6. In section `<list name="GeometryForNormals">` you have to export the shapes to the file `[CaseName]_hdp_Actual.vtk` by adding
  `<shapeout file="hdp" />`

7. Keep the section to configure the vector normal creation, where you indicate which is the boundary interface (`<geometryfile file="[CaseName]_hdp_Actual.vtk"`)
```
  <normals>
    <distanceh value="2.0" comment="Maximum distance (H*distanceh) to compute normals data (default=2)" />
    <geometryfile file="[CaseName]_hdp_Actual.vtk" comment="File with boundary geometry (VTK format)" />
    <svshapes value="1" comment="Saves VTK with geometry in triangles and quads with its normals for debug (default=0)" />
  </normals>

```
