### ISSUE TITLE
Ask for help with a paper

### ISSUE THREAD

**Issue by lk650** [DualSPHysics/DualSPHysics#161]
I'd like to ask for help with a paper that "Evaluation of reliability and efficiency of different boundary conditions in an SPH code"

**Comment by jialing95** [comment]
Hi, the paper you mentioned is a conference paper which may not be exhaustive, but I think another journal paper will meet your expectation:

**Modified dynamic boundary conditions (mDBC) for general-purpose smoothed particle hydrodynamics (SPH): application to tank sloshing, dam break and fish pass problems**
https://link.springer.com/article/10.1007/s40571-021-00403-3

**Comment by lk650** [comment]
Thank you very much for your reply











在 2024-01-20 15:40:15，"Jialing Dai" ***@***.***> 写道：

Hi, the paper you mentioned is a conference paper which may not be exhaustive, but I think another journal paper will meet your expectation:

Modified dynamic boundary conditions (mDBC) for general-purpose smoothed particle hydrodynamics (SPH): application to tank sloshing, dam break and fish pass problems
https://link.springer.com/article/10.1007/s40571-021-00403-3
