### ISSUE TITLE
Dambreak 3D example: Parameter "-gpu" unrecognised or invalid

### ISSUE THREAD

**Issue by jialing95** [DualSPHysics/DualSPHysics#162]
[DamBreak.31384168.zip](https://github.com/DualSPHysics/DualSPHysics/files/13930835/DamBreak.31384168.zip)
When I run (**xCaseDambreak_linux64_GPU.sh**) on ibex cluster, the code failed quickly. And then I checked the file (DamBreak.31384168.out), found:

```
GenCase v5.0.278c (30-10-2023)
===============================
LoadDsphConfig> .../bin/linux/DsphConfig.xml

*** Exception (JGenCfgRun::ErrorParm) at JMDominguez/codes/GenCase/source/JCfgRunBase.cpp:139
Text: Parameter "-gpu" unrecognised or invalid. (Level cfg:0, Parameter:0)


Finished execution (code=1).

Execution aborted.

```

Can anyone help me with this issue, thanks!

**Comment by imestevez** [comment]
As the error says: "Parameter "-gpu" unrecognised or invalid". 
GenCase does not support that option, so you should remove the `-gpu` parameter from the GenCase call in your `xCaseDambreak_linux64_GPU.sh`

**Comment by jialing95** [comment]
Hi, I checked that file and only to find one place containing `gpu`.

but if I remove this line:

`export dualsphysicsgpu="${dirbin}/DualSPHysics5.2_linux64"`

How can this .sh file run without specifying any parameters w.r.t gpu or cpu?

I've emailed to ibex team of university, and I believe something wrong lies in the deployment of GPU resources. I will get back to you soon. Thanks for your help!

**Comment by jialing95** [comment]
Hi, I actually don't understand the lines w.r.t **export dualsphysicsgpu** and **dualsphysicscpu**:

1) If I use **GPU** resources, I should comment out export dualsphysicscpu? vice versa

2) I couldn't find /DualSPHysics5.2CPU_linux64 and /DualSPHysics5.2_linux64 under the directory of /GenCase_linux64. Are those two folders created after running .sh file?

3) If I don't make any changes to the directories above, it will fail instantly. However, if I comment them out, and add a new line: `export dualsphysicsgpu="${dirbin}/GenCase_linux64"`, it keeps running and seems a solution. Why?

![image](https://github.com/DualSPHysics/DualSPHysics/assets/118798409/dcf431e0-cdc7-4e22-84e3-a23e08feb240)

**Comment by jialing95** [comment]
The problem is solved now after I get to know some details of how to use GPU on ibex clusters. 

I just need to change some directories. The total run time is only 1 minute.
