### ISSUE TITLE
MoorDyn v2

### ISSUE THREAD

**Issue by sanguinariojoe** [DualSPHysics/DualSPHysics#169]
More than one year ago I kindly asked you to come back to the MoorDyn upstream instead of using your own fork. The issue was closed without even a single comment on why.

Anyway, I am kindly asking you to consider coming back to the upstream. This time I am elaborating a bit more the reasons:

# Legal issues

I am really surprised you did not realized on this before, but your are breaking the MoorDyn license. The Moordyn you forked is GPL (v3):

https://github.com/imestevez/MoorDynPlus/blob/master/LICENSE

while DualSphysics is LGPL:

https://github.com/DualSPHysics/DualSPHysics/blob/master/LICENSE

This **is not** a minor issue. A lawyer might totally crush you guys.

Fortunately, the new MoorDyn has been relicensed:

https://github.com/FloatingArrayDesign/MoorDyn/blob/master/LICENSE.txt

# Technical deficiencies

## Memory errors and bugs

There are some errors that are rather evident taking a fast look to the code, like the following line:

https://github.com/imestevez/MoorDynPlus/blob/master/src/source/Line.cpp#L207

A memset over a class filled with vectors.

Anyway, you can just run any static analyzer on MoorDynPlus and cry. I do not even dare to process the valgrind log.

## Lack of features

The new MoorDyn includes many desirable features you are lacking here, like bodies, rods, nonlinear properties...

## Euler time marching for the loose coupling is forced

Because you cannot save and restore the state of MoorDyn, you are forced to do an Euler time marching, no matters what time scheme you consider on any of the coupled sims. The proof:

https://github.com/DualSPHysics/DualSPHysics/blob/master/src/source/JSphCpuSingle.cpp#L1009

That is of course suboptimal, specially close to the natural frequency of the line.

**Comment by alexbexe** [comment]
No toques los cojones

**Comment by sanguinariojoe** [comment]
> No toques los cojones

Se respira el amor! Si señor!

**Comment by alexbexe** [comment]
don't touch the balls
