### ISSUE TITLE
PartVTK missing -SaveResume flag

### ISSUE THREAD

**Issue by jgphpc** [DualSPHysics/DualSPHysics#173]
Hi,

[PartVTKOut_Help](https://github.com/DualSPHysics/DualSPHysics/blob/develop/doc/help/PartVTKOut_Help.out#L57) says:
```
-SaveResume <file.csv>  Generates CSV file with resume info
```
While this is not used (commented out) in the examples of the git repo, I do see `-SaveResume` used for example in the zip:
DualSPHysics_v5.2/examples/inletoutlet/01_FlowCylinder/xCaseFlowCylinder_Re020_linux64_GPU.sh
The issue is that `-SaveResume` is not supported:
```
Text: Parameter "-SaveResume" unrecognised or invalid. (Level cfg:0, Parameter:4)
```

Not a big issue, just want to notify you.

**Comment by imestevez** [comment]
I could not replicate that issue.
Try again with the latest package (v5.2.2) from: https://dual.sphysics.org/downloads/

**Comment by jgphpc** [comment]
> I could not replicate that issue.

My bad: I was calling `PartVTK_linux64` instead of `PartVTKOut_linux64`, sorry for the noise.
