### ISSUE TITLE
Problema di menisco fluido

### ISSUE THREAD

**Issue by matte-giuf** [DualSPHysics/DualSPHysics#207]
Salve,

sto effettuando uno studio sul comportamento di un fluido all'interno di un contenitore cilindrico durante un moto circolare. Ho notato che il pelo libero del fluido si dispone come in figura, sollevando la mia attenzione.

![Immagine WhatsApp 2024-06-27 ore 10 18 55_a1450b44](https://github.com/DualSPHysics/DualSPHysics/assets/173997603/fb08479c-8af9-4960-951c-9dd33667c7e8)

Chiedevo gentilmente come poter risolvere questo problema.
Ho provato anche a seguire la guida su mDBC, pensando potessi risolvere, ma non sono riuscito nell'intento.

Ringrazio in anticipo.

**Comment by giosans** [comment]
Non ho una risposta, ma consiglio di ripostare in inglese. Qui o nel Forum.

**Comment by matte-giuf** [comment]
> Non ho una risposta, ma consiglio di rispondere in inglese. Qui o nel Forum.

thank you, i've solved it with mDBC conditions instead DBC
