### ISSUE TITLE
Wiki formulas barely readable

### ISSUE THREAD

**Issue by giosans** [DualSPHysics/DualSPHysics#219]
The wiki is very nice! However, formulas are presented as images, and their vertical size makes the text hard to read. 

> ![image](https://github.com/user-attachments/assets/0b18345e-8228-4afc-baaf-ba0031abcbc7)

Also, if you are in dark mode, it gives this sort of output:

> ![image](https://github.com/user-attachments/assets/d2636dde-bb28-4b0e-af7d-9c66936004b3)

Is there a reason for using images in place of LateX formatted text? If not, are you planning to convert the Wiki formulas as LateX formatted text, sooner or later?

Thank you!

**Comment by imestevez** [comment]
We are working on a new wiki that fixes this issues
