### ISSUE TITLE
Normal vectors to an object moving in the plane

### ISSUE THREAD

**Issue by matte-giuf** [DualSPHysics/DualSPHysics#231]
Hello everybody, I have a question.

I have a fluid in a cylindrical tank that moves with a specific motion. How can I define the normals to it in order to use mDBC conditions?

Thank you all.

**Comment by imestevez** [comment]
The normals should be defined pointing to the fluid.
You can check this thread to get more information: https://github.com/DualSPHysics/DualSPHysics/issues/156
Aditionally, in the full package (https://dual.sphysics.org/downloads/) you will find several working cases on using mDBC in the folder examples/mdbc

**Comment by matte-giuf** [comment]
> The normals should be defined pointing to the fluid. You can check this thread to get more information: #156 Aditionally, in the full package (https://dual.sphysics.org/downloads/) you will find several working cases on using mDBC in the folder examples/mdbc

Thank you so much for  your detailed reply, I'll try.
