### ISSUE TITLE
Fluid removal

### ISSUE THREAD

**Issue by matte-giuf** [DualSPHysics/DualSPHysics#235]
Hello everybody,

If I want to remove some fluid from a tank by a cylindrical duct, what can I do??
I try to use inlet/outlet example, but I can't remove fluid, only add it.

Thanks all

**Comment by imestevez** [comment]
You can use `<setmkvoid />` followed by the geometry you want. You can see an example in: https://github.com/DualSPHysics/DualSPHysics/blob/ecf3e9a98fcc3957840dd11b9973c5c60e134065/examples/main/01_DamBreak/CaseDambreak_Def.xml#L40-L45

**Comment by matte-giuf** [comment]
I see the example, but maybe I explained myself wrongly, or I don't understand, sorry. 
I would like to draw fluid, from a pipe, so as to lower the initial water level in the tank.

**Comment by imestevez** [comment]
Please, post your question to the forum: https://github.com/DualSPHysics/DualSPHysics/discussions
