### ISSUE TITLE
How to choose GPU_blocksize?

### ISSUE THREAD

**Issue by JUN-D228** [DualSPHysics/DualSPHysics#245]
I am a beginner. I saw mention of blocksize in section 5.5 of the user manual：

“An important novelty since v4.0 is the determination of the optimum Blocksize for CUDA kernels that excute particle interaction......”

 but I didn’t find any settings related to blocksize in the provided case templates and examples. Therefore, I would like to ask how to set the blocksize.

**Comment by imestevez** [comment]
This issue is discussed in https://github.com/DualSPHysics/DesignSPHysics/issues/221
