### ISSUE TITLE
How to combine waves with flexible structures？

### ISSUE THREAD

**Issue by haozhibin123** [DualSPHysics/DualSPHysics#257]
When I make waves, I change DualSPHysics5.2_win64.exe to DualSPHysics5.2_FlexStruc_win64.exe. Why do I get an error?

**Comment by imestevez** [comment]
Could you show the error?

**Comment by haozhibin123** [comment]
Hello, thank you for your reply. For example, I modified the wCaseWaveTank_DBC_win64_GPU.bat file in the ..\DualSPHysics_v5.2.2\DualSPHysics_v5.2\examples\mdbc\06_WaveTank folder and changed the "set dualsphysicscpu="%dirbin%/DualSPHysics5.2CPU_win64.exe""
and "set dualsphysicsgpu="%dirbin%/DualSPHysics5.2_win64.exe"" changed to "set dualsphysicscpu="%dirbinflexstruc%\DualSPHysics5.2_FlexStrucCPU_win64.exe"" and
"set dualsphysicsgpu="%dirbinflexstruc%\DualSPHysics5.2_FlexStruc_win64.exe"", and add "set dirbinflexstruc="%dirbin%\FlexStruc"", m
![1729175517317](https://github.com/user-attachments/assets/18f4dff5-145f-4563-8793-c8a474a179ab)
y purpose is to first test whether using "DualSPHysics5.2_FlexStruc_win64.exe" can run the pistion to create waves, but unfortunately I can't do this. The error is as shown in the picture, I hope to get your answer.

**Comment by haozhibin123** [comment]
Hello, thank you for your reply. For example, I modified the wCaseWaveTank_DBC_win64_GPU.bat file in the ..\DualSPHysics_v5.2.2\DualSPHysics_v5.2\examples\mdbc\06_WaveTank folder and changed the "set dualsphysicscpu="%dirbin%/DualSPHysics5.2CPU_win64.exe""
and "set dualsphysicsgpu="%dirbin%/DualSPHysics5.2_win64.exe"" changed to "set dualsphysicscpu="%dirbinflexstruc%\DualSPHysics5.2_FlexStrucCPU_win64.exe"" and
"set dualsphysicsgpu="%dirbinflexstruc%\DualSPHysics5.2_FlexStruc_win64.exe"", and add "set dirbinflexstruc="%dirbin%\FlexStruc"", my purpose is to first test whether using "DualSPHysics5.2_FlexStruc_win64.exe" can run the push board to create waves, but unfortunately I can't do this. The error is as shown in the picture, I hope to get your answer.
![屏幕截图 2024-11-15 162827](https://github.com/user-attachments/assets/24dd63bd-43a6-4d26-8438-21a7f8ee677e)

**Comment by haozhibin123** [comment]
I only performed the above operations, I don’t know if other operations are needed.

**Comment by imestevez** [comment]
I think you are not defining the path correctly. 
Try with:

```
set dirbin=..\..\..\bin\windows
set dirbinflexstruc="%dirbin%\FlexStruc"
set gencase="%dirbin%\GenCase_win64.exe"
set dualsphysicscpu="%dirbinflexstruc%\DualSPHysics5.2_FlexStrucCPU_win64.exe"
set dualsphysicsgpu="%dirbinflexstruc%\DualSPHysics5.2_FlexStruc_win64.exe"
```

**Comment by haozhibin123** [comment]
Thank you very much for your reply and answer. I would also like to ask you, what is the difference between "\" and "/"? Why do some programs have "\" and some have "/"? Which one is the correct way to write it?

**Comment by haozhibin123** [comment]
Thank you very much for your reply and answer. I would also like to ask you, what is the difference between "\" and "/"? Why do some programs have "\" and some have "/"? Which one is the correct way to write it?

**Comment by haozhibin123** [comment]
Thank you very much for your reply and answer. The program has been successfully run. But I still have a question. The "\" in the former of "dirbin=../../../bin/windows" and "dirbin=..\..\..\bin\windows" is wrong. Of? But I found that the "/" in...\DualSPHysics_v5.2.2\DualSPHysics_v5.2\examples\main\06_Wavemaker\wCaseWavemaker_win64_GPU.bat are all "\" tilted to the right.

**Comment by imestevez** [comment]
`\` is used on Windows while `/` is used on Linux
