### ISSUE TITLE
Coupling with CHRONO

### ISSUE THREAD

**Issue by joeelrahi** [DualSPHysics/DualSPHysics#26]
Hello,

That's not an issue as much as it is a question directed to the developers:

 I wish to calculate the deflection of a solid structure due to fluid force, I understand one possibility would be to use a hinge with a restoring force (from the examples).

However, I am more interested in 2 way coupling for fluid-solid interaction for flexible beams !! is it already implemented in the latest version?

thanks in advance,
Joe

**Comment by jmdalonso** [comment]
No, this feature is not implemented in the current version, but you could
implement it.

Best regards,
Jose

>

**Comment by joeelrahi** [comment]
Hello,

I'm working on this at the moment, and I think I might need to look through the source files used to compile "dsphchrono.dll" ; would you be able to provide them?

thanks in advance,
Joe

**Comment by elieobeid7** [comment]
Hello Joe, what you want is most probably here

https://github.com/DualSPHysics/DualSPHysics/search?q=dsphchrono&unscoped_q=dsphchrono

It's one of these files

this is the main file

https://github.com/DualSPHysics/DualSPHysics/blob/b6c3d8de954957ae53b510c69466947cadc338a6/src/source/DSPHChronoLib.h

and the others are dependencies
