### ISSUE TITLE
How to generate different types of fluid particles in the same place？

### ISSUE THREAD

**Issue by csusu953** [DualSPHysics/DualSPHysics#266]
Dear Developers，
I would like to know if it is possible to generate different types of particles at the same spatial location during initialization through an XML file, and how to achieve this?
For example, in the multiphase flow case, I defined two types of fluid particles with different viscosities (marked by MK=1 and MK=2), and I hope to make the spatial positions of these two types of particles overlap during initialization. In the XML file, I used the same geometric modeling parameters for the two types of fluid particles. However, the program would terminate and indicate that the fluid particles were not successfully generated.
Can anyone give some advice, please? thank you very much!

**Comment by imestevez** [comment]
Discussed here: https://github.com/DualSPHysics/DualSPHysics/discussions/265
