### ISSUE TITLE
Porting to HIP/ROCm (for AMD GPU and heterogeneous computing support)

### ISSUE THREAD

**Issue by kwahoo2** [DualSPHysics/DualSPHysics#3]
First of all, thank you for this great project!

I want to ask if there are any plans for porting CUDA code to ROCm https://github.com/RadeonOpenCompute/ROCm ?

There are at least 2 reasons for such port:

a)support for AMD GPU's  
b)support for heterogeneous computing with CPU's and GPU's working together seamlessly 

I ran examine tool as shown in the porting manual https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/Programming_Guides/HIP-porting-guide.rst and got:

```
DualSPHysics/SOURCE/DualSPHysics/Source$ hipexamine-perl.sh .
info: converted 1 CUDA->HIP refs( dev:0 mem:0 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:1 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:43 in './JObjectGpu.h'
info: converted 5 CUDA->HIP refs( dev:0 mem:0 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:5 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:48 in './JObjectGpu.cpp'
info: converted 1 CUDA->HIP refs( dev:0 mem:0 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:1 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:269 in './JSphGpu.h'
info: converted 39 CUDA->HIP refs( dev:0 mem:2 kern:4 coord_func:26 math_func:0 special_func:1 stream:0 event:0 err:4 def:0 tex:0 extern_shared:2 other:0 ) warn:0 LOC:218 in './JWaveOrder2_ker.cu'
info: converted 27 CUDA->HIP refs( dev:2 mem:8 kern:0 coord_func:0 math_func:0 special_func:0 stream:6 event:11 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:173 in './FunctionsCuda.h'
  warning: ./FunctionsCuda.cpp:#141 :   cudaRuntimeGetVersion(&runtimeVersion);
info: converted 73 CUDA->HIP refs( dev:15 mem:54 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:4 def:0 tex:0 extern_shared:0 other:0 ) warn:1 LOC:603 in './FunctionsCuda.cpp'
info: converted 26 CUDA->HIP refs( dev:0 mem:20 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:6 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:485 in './JCellDivGpu.cpp'
info: converted 152 CUDA->HIP refs( dev:5 mem:142 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:5 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:1456 in './JSphGpu.cpp'
info: converted 6 CUDA->HIP refs( dev:0 mem:0 kern:0 coord_func:0 math_func:0 special_func:0 stream:6 event:0 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:73 in './JReduSum_ker.h'
  warning: ./JTimerCuda.h:#23 : //:#   de tiempo mediante la GPU usando cudaEvent de CUDA. (10-01-2011)
  warning: ./JTimerCuda.h:#37 : /// \brief Defines a class to measure short time intervals on the GPU using cudaEvent.
info: converted 9 CUDA->HIP refs( dev:0 mem:0 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:9 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:2 LOC:73 in './JTimerCuda.h'
info: converted 14 CUDA->HIP refs( dev:0 mem:0 kern:2 coord_func:12 math_func:0 special_func:0 stream:0 event:0 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:131 in './JCellDivGpuSingle_ker.cu'
info: converted 74 CUDA->HIP refs( dev:0 mem:24 kern:3 coord_func:30 math_func:0 special_func:1 stream:9 event:0 err:4 def:0 tex:0 extern_shared:3 other:0 ) warn:0 LOC:565 in './JReduSum_ker.cu'
info: converted 169 CUDA->HIP refs( dev:0 mem:22 kern:13 coord_func:125 math_func:0 special_func:1 stream:0 event:0 err:0 def:0 tex:0 extern_shared:8 other:0 ) warn:0 LOC:925 in './JCellDivGpu_ker.cu'
info: converted 3 CUDA->HIP refs( dev:0 mem:3 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:233 in './JArraysGpu.cpp'
  warning: ./JSphGpu_ker.cu:#939 :     cudaOccupancyMaxPotentialBlockSize(&mingridsize,&qblocksize,(void*)ptr,0,0);
  warning: ./JSphGpu_ker.cu:#940 :     struct cudaFuncAttributes attr;
  warning: ./JSphGpu_ker.cu:#941 :     cudaFuncGetAttributes(&attr,(void*)ptr);
  warning: ./JSphGpu_ker.cu:#951 :     cudaOccupancyMaxPotentialBlockSize(&mingridsize,&qblocksize,(void*)ptr,0,0);
  warning: ./JSphGpu_ker.cu:#952 :     struct cudaFuncAttributes attr;
  warning: ./JSphGpu_ker.cu:#953 :     cudaFuncGetAttributes(&attr,(void*)ptr);
  warning: ./JSphGpu_ker.cu:#1291 :     cudaOccupancyMaxPotentialBlockSize(&mingridsize,&qblocksize,(void*)ptr,0,0);
  warning: ./JSphGpu_ker.cu:#1292 :     struct cudaFuncAttributes attr;
  warning: ./JSphGpu_ker.cu:#1293 :     cudaFuncGetAttributes(&attr,(void*)ptr);
info: converted 344 CUDA->HIP refs( dev:0 mem:13 kern:60 coord_func:238 math_func:0 special_func:1 stream:0 event:18 err:10 def:0 tex:0 extern_shared:4 other:0 ) warn:9 LOC:2879 in './JSphGpu_ker.cu'
info: converted 9 CUDA->HIP refs( dev:0 mem:4 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:5 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:473 in './JGauge.cpp'
info: converted 9 CUDA->HIP refs( dev:0 mem:9 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:732 in './JSphGpuSingle.cpp'
info: converted 1 CUDA->HIP refs( dev:0 mem:0 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:1 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:192 in './JGauge.h'
info: converted 21 CUDA->HIP refs( dev:0 mem:0 kern:2 coord_func:13 math_func:0 special_func:1 stream:0 event:0 err:4 def:0 tex:0 extern_shared:1 other:0 ) warn:0 LOC:315 in './JGauge_ker.cu'

info: TOTAL-converted 983 CUDA->HIP refs( dev:22 mem:301 kern:84 coord_func:444 math_func:0 special_func:5 stream:21 event:38 err:50 def:0 tex:0 extern_shared:18 other:0 ) warn:12 LOC:49391
  warning: unconverted cudaFuncAttributes : 3
  warning: unconverted cudaOccupancyMaxPotentialBlockSize : 3
  warning: unconverted cudaFuncGetAttributes : 3
  warning: unconverted cudaEvent : 2
  warning: unconverted cudaRuntimeGetVersion : 1
  kernels (6 total) :   KerComputeDampingPla(1)  KerInteractionGaugeVel(1)  KerCalcPosition1(1)  KerPreSortFluid(1)  KerSortDataParticles(1)  KerReduSumUint(1)

```

The tool converted 983 refs automatically but there are still 12 unconverted refs that have to be converted by the developer.

---

Some background/case study about porting to ROCm by CAFFE developer https://www.youtube.com/watch?v=I7AfQ730Zwc

**Comment by kwahoo2** [comment]
Some initial work (fails to build) https://github.com/kwahoo2/DualSPHysics/commit/746bce429d249818eb503d518e59411afa7318e1

**Comment by ndrs92** [comment]
Hi there!

First of all, thanks for the suggestion and your work trying to adapt the code to ROCm. As you can see the code does not use a lot of fancy CUDA instructions so it is pretty straightforward to convert.

I'm not a developer on the DualSPHysics code but after debating this with its main developer we talked about the possibility of making the code friendlier for converting, especially on the static libraries. So the CUDA code could be removed from the libraries and used outside them (as far as I understand).

We, currently, have no interest in mantaining a ROCm version of the code, as for now there are a lot of side, private, developments on this main one that consume most of the developers time, but adapting the code to be easily convertible could be done.

Sorry for not proposing an immediate solution but I'll keep this issue open so in the near future, when the code is ready, can do something about it.

Again, thanks for the suggestion and your work!

**Comment by zlotny** [comment]
Hi again.

Recently there were a lot of new changes on the DualSPHysics code. Those changes include removing that CUDA code from static libraries so porting this to ROC was easier.

Could you try now to translate the code? Thanks for your work!

**Comment by kwahoo2** [comment]
Hi,

I'm back after a long absence, because I hadn't a ROCm-capable GPU. It took AMD years to add RDNA-based GPU's to ROCm. 

At this point I am able to convert and compile the code, but the linker fails.
For some reason the linker cannot find a symbol for std::max
```
ld.lld: error: undefined symbol: max(float, float)
>>> referenced by JSphCpu.cpp
>>>               JSphCpu.o:(.omp_outlined..26)
>>> referenced by JSphCpu.cpp
>>>               JSphCpu.o:(.omp_outlined..27)
>>> referenced by JSphCpu.cpp
>>>               JSphCpu.o:(.omp_outlined..28)
>>> referenced 100 more times
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:138: ../../bin/linux/DualSPHysics5.0_linux64] Błąd 1
```

For testing purposes, there is linking in a single command:

```
hipcc -o DualSPHysics5.0_linux64 JXml.o tinystr.o tinyxml.o tinyxmlerror.o tinyxmlparser.o JMotion.o JMotionList.o JMotionMov.o JMotionObj.o JMotionPos.o JDsMotion.o Functions.o FunGeo3d.o FunSphKernelsCfg.o JAppInfo.o JBinaryData.o JCfgRunBase.o JDataArrays.o JException.o JLinearValue.o JLog2.o JObject.o JOutputCsv.o JRadixSort.o JRangeFilter.o JReadDatafile.o JSaveCsv2.o JTimeControl.o randomc.o JDsphConfig.o JDsPips.o JPartDataBi4.o JPartDataHead.o JPartFloatBi4.o JPartOutBi4Save.o JCaseCtes.o JCaseEParms.o JCaseParts.o JCaseProperties.o JCaseUserVars.o JCaseVtkOut.o JArraysCpu.o JCellDivCpu.o JSphCfgRun.o JComputeMotionRef.o JDsDamping.o JDsGaugeItem.o JDsGaugeSystem.o JDsPartsOut.o JDsSaveDt.o JSphShifting.o JSph.o JDsAccInput.o JSphCpu.o JDsInitialize.o JFtMotionSave.o JSphMk.o JDsPartsInit.o JDsFixedDt.o JDsViscoInput.o JDsOutputTime.o JWaveAwasZsurf.o JWaveSpectrumGpu.o main.o JCellDivCpuSingle.o JPartsLoad4.o JSphCpuSingle.o FunctionsCuda.o JObjectGpu.o JArraysGpu.o JDebugSphGpu.o JCellDivGpu.o JSphGpu.o JCellDivGpuSingle.o JSphGpuSingle.o JCellDivGpu_ker.o JCellDivGpuSingle_ker.o JDsPips_ker.o JDsGauge_ker.o JReduSum_ker.o JSphShifting_ker.o JDsAccInput_ker.o JSphGpu_ker.o JSphGpuSimple_ker.o JWaveOrder2_ker.o JMLPistonsGpu.o JRelaxZonesGpu.o JRelaxZone_ker.o JChronoObjects.o JDsMooredFloatings.o JDsFtForcePoints.o JSphCpu_InOut.o JSphCpuSingle_InOut.o JSphBoundCorr.o JSphInOut.o JSphInOutZone.o JSphInOutGridData.o JSphInOutPoints.o JSphInOutVel.o JSphInOutVelAwas.o JSphInOutZsurf.o JSimpleNeigs.o JSphGpuSingle_InOut.o JPartNormalData.o JNormalsMarrone.o -D_GLIBCXX_USE_CXX11_ABI=0 -fopenmp -lgomp -ldl -lrt -L./ -L../lib/linux_gcc -ljvtklib_64 -ljnumexlib_64 -ldsphchrono -lChronoEngine -lChronoEngine_parallel -ljwavegen_64 -ldsphmoordyn_64

```

**Comment by kwahoo2** [comment]
Good news, I've got the DualSPHysics working on an AMD GPU!
https://github.com/kwahoo2/DualSPHysics

[Screenshot](https://i.imgur.com/dM561pf.png)

Performance difference is quite noticeable, testing the 01_DamBreak:
**CPU**, Ryzen 7 1700:
**real    50m35,257s**
user    749m2,203s
sys     0m14,726s

**GPU**, Radeon 6600XT
**real    4m55,682s**
user    6m55,447s
sys     0m6,649s

If there is any interest in including ROCm/HIP support in main DualSPHysics, we should talk how it should be done. There are at least two ways: 
A) just separating CUDA and HIP code with ifdefs 
or 
B) making a single HIP codebase targeting both CUDA and AMD ROCm.

**Comment by AhmedSalih3d** [comment]
> 

Really interesting stuff! So this means that basically on newer AMD cards? Could you elaborate a bit more on this?

I have always felt that it would be extremely nice to have a open-source project not connected to a specific vendor, so I think this is a really great step.

Basically you use the exact same code as written for Nvidia, but just compile it differently? So there is no hassle i.e. you do not need to maintain two separate GPU codes?

I ask mainly of my own curiosity.

Kind regards

**Comment by kwahoo2** [comment]
> > 
> 
> Really interesting stuff! So this means that basically on newer AMD cards?

As of ROCm 4.5.0: AMD Vega, CDNA, RDNA2 cards are supported. If you would like to run it on older cards (Polaris), you have to use an older ROCm release.
ROCm currently works on Linux, check [supported operating systems list.](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html)

> Basically you use the exact same code as written for Nvidia, but just compile it differently? So there is no hassle i.e. you do not need to maintain two separate GPU codes?

There is a script that converts all the code to [HIP code](https://github.com/ROCm-Developer-Tools/HIP). 
Quoting the HIP description:

>HIP is a C++ Runtime API and Kernel Language that allows developers to create portable applications for AMD and NVIDIA GPUs from single source code.
