### ISSUE TITLE
Define Constants window cannot be opened

### ISSUE THREAD

**Issue by WangJJ666** [DualSPHysics/DualSPHysics#31]
After clicking the Define Constants button, nothing happens and no dialog box appears. The error window says:

*** Exception (JSphCpuSingle::VisuConfig)
Text: Constant 'b' cannot be zero.
'b' is zero when fluid height is zero (or fluid particles were not created)

Finished execution (code=1).

The Define Constants window cannot be opened, so I cannot set this ‘b’ constant.

**Comment by jmdalonso** [comment]
This error message is shown when the constant b is zero.
b is zero when no fluid particles or gravity is zero. Checks the configuration.
