### ISSUE TITLE
Is parallel GPU processing possible?  

### ISSUE THREAD

**Issue by jb4earth** [DualSPHysics/DualSPHysics#33]
Is it possible to run a single simulation on multiple GPU? 

I am running into memory limits from my current GPU. If the answer is no, I did see that running in parallel on CPU is an option.

**Comment by jmdalonso** [comment]
We are working on it but it is not yet available.

**Comment by Sal-AL** [comment]
Similar to the above question, is parallel cpu processing possible?

**Comment by jmdalonso** [comment]
Yes, it is using OpenMP.

Best regards,
jose

**Comment by yboy23** [comment]
Hi,I see that the latest version 5.2 has been released, is GPU parallel computing supported now?

**Comment by imestevez** [comment]
Hello, multi-GPU is not available yet. You can find the novelties included in v5.2 here: https://github.com/DualSPHysics/DualSPHysics/wiki/9.-New-in-DualSPHysics

**Comment by Rindu260801** [comment]
hi, parallel processing with gpu is available, currently im using cuda for this, but im still struggling with the DesighSPHysic for my model
