### ISSUE TITLE
How to run a testcase DamBreak

### ISSUE THREAD

**Issue by awaixzaman3703** [DualSPHysics/DualSPHysics#35]
I just started using DualSPHysics as a beginner and I wanted to run a testcase Dambreak but I could not. Can someone wrote down the step wise procedure how to do it ? I read the manual but it does not help me because I don't understand how to start with it.

Regards,

**Comment by jmdalonso** [comment]
It is pretty easy. Download DualSPHysics Package from https://dual.sphysics.org/index.php/downloads/ and execute the included scripts (.bat for Windows and .sh for Linux). If you do not have a GPU, run them on the CPU. To use the GPU you must update its driver.

Best regards,
