### ISSUE TITLE
Part_Head.ibi4 file not found in data directory ?

### ISSUE THREAD

**Issue by awaixzaman3703** [DualSPHysics/DualSPHysics#37]
Dear all,
I have done the simulations with one of the case study and DualSPHysics shows that simulations finished but for post processing it shows an error indicating that Part_head.ibi4 file not found in data directory but I can see the file in the data folder. can anybody tells me what is this problem ?
 regards,
Muhammad Awais Zaman

**Comment by jmdalonso** [comment]
The path indicated in the post-processing tool must be wrong.
