### ISSUE TITLE
Coupling multiple rot/lin motion data files within timeline

### ISSUE THREAD

**Issue by HHOPs** [DualSPHysics/DualSPHysics#38]
Dear all, I just wanted to verify that it is currently not possible to add multiple motion files (recorded test-bench motion) to the motion setup and run them in parallel (e.g. rot around x, rot around y etc.)? Is there a workaround wrt. to the introduction of real-world data for respective SPH analysis? Thanks and best regards, Richard

**Comment by jmdalonso** [comment]
Yes, it is possible. You can find complex examples using predefined motion in the DualSPHysics package available at https://dual.sphysics.org/index.php/downloads/
