### ISSUE TITLE
How to remove error "Part_Head.ibi4 file not found in data directory?"

### ISSUE THREAD

**Issue by awaixzaman3703** [DualSPHysics/DualSPHysics#39]
Hi Everyone,
I am new user of DualSPHysics and I have finished the simulations for a 2D case but it shows the error of part_Head.ibi4 file not found in data directory ? Can I anyone help from where can I solve this error.
I can send my XML file and Batch file as well if someone can help me with that.

Kind Regards,
Awais Zaman
(muhammad.zaman@nottingham.ac.uk)

**Comment by jmdalonso** [comment]
The path indicated to the post-processing program must be wrong. You can find several examples in the DualSPHsysics package available at https://dual.sphysics.org/index.php/downloads
