### ISSUE TITLE
Help! CODE_SIZE4 complie error

### ISSUE THREAD

**Issue by aerose1st** [DualSPHysics/DualSPHysics#43]
Because many floating objects need to be analyzed, CODE_SIZE4 in DualSphDef.h was activated. Then I compiled the files. However, an error occurred in JDebugSphGpu.cpp (JDebugSphGpu::LoadParticlesData). 
When CODE_SIZE4 was disabled, it was compiled without any problem.
How can I fix this problem?

Error code: JDebugSphGpu.cpp:229:56: error: cannot convert 'typecode* const {aka unsigned int* const}' to 'const word* {aka const short unsigned int*}' for argument '3' to ~

Linux, g++ v4.85, CUDA v9.2, makefile

**Comment by jmdalonso** [comment]
This problem was fixed in version 5.0 beta

**Comment by aerose1st** [comment]
How long does it take to get version 5? Can't I test it right away?

**Comment by aerose1st** [comment]
> This problem was fixed in version 5.0 beta

How long does it take to get version 5? Can I test it right away?

**Comment by jmdalonso** [comment]
Version 5.0 beta is available for 5th DualSPHysics Users Workhop attendess. Final version 5.0 will be available for everyone in a few months.
Anyway, this problem was also fixed in the current code in the repository (branch develop).

**Comment by aerose1st** [comment]
First of all, let's thank you for the quick fix.
The below error occurred after compiling the latest version you modified and then re-executing it.

 *** Exception (JSphGpuSingle::ConstantDataUp) at JSphGpu.cpp:534
Text: Failed copying constants to GPU. (CUDA error 13 (invalid device symbol)).
