### ISSUE TITLE
Chrono - bodymoving problem

### ISSUE THREAD

**Issue by aerose1st** [DualSPHysics/DualSPHysics#45]
For Chrono, **bodyfixed** and **bodyfloating** work well.
However, in the case of **bodymoving**, it is included in the code but ends with a warning on execution.
Is this a problem of Chrono or a problem of DualSPHysics?
If I ignore this warning and execute it, will I get the wrong result?

**Comment by jmdalonso** [comment]
The option bodymoving is still under development.
