### ISSUE TITLE
Viscosity an Reynolds number

### ISSUE THREAD

**Issue by Grigor72** [DualSPHysics/DualSPHysics#48]
So 
first off all i would like to thank you for perfect organized workshop in Ourense
let say ive just started to deciphe xml case files and would like to ask
1. which one viscosity is used regarding to Reynolds number in FlowCylinder cas files
2.As i have to go in my case to higher Reynolds numbers 5000-10000 do you have some more info about turbulence model implemented in application (like validation articles)

regards Grigor

**Comment by atafuni** [comment]
Hi,
For the viscosity, the value is calculated to have a desired Reynolds number: U*D*nu^(-1).
So you can change any of these parameters to achieve your desired Reynolds number.

For turbulence, there is the laminar+SPS model that you can use. 
Please read the guide for equations and more info about it.
We are currently also working on additional turbulence model for future releases.

Best,
Angelo Tafuni
