### ISSUE TITLE
03_WavesMoorings3D Windows and Linux

### ISSUE THREAD

**Issue by Grigor72** [DualSPHysics/DualSPHysics#52]
So
i continue with my case at the end i have successfull imorted KCS geometry and applied body mass properties. After model was prepared in Windows (it works under windos) i would like to move on Centos7 28 cores server mashine by using CPU power and some issues appear i seems like the solver does not evaluate iso surface.
For test i started xCaseMoorings3D_linux64_CPU.sh and wCaseMoorings3D_win64_CPU.bat it works under windows unlike on Linux the same issue appears
![Untitled](https://user-images.githubusercontent.com/63708484/84897356-1b7a0100-b0ae-11ea-878b-266b05e8e565.png)
regards Grigor

**Comment by chenxin202** [comment]
> So
> i continue with my case at the end i have successfull imorted KCS geometry and applied body mass properties. After model was prepared in Windows (it works under windos) i would like to move on Centos7 28 cores server mashine by using CPU power and some issues appear i seems like the solver does not evaluate iso surface.
> For test i started xCaseMoorings3D_linux64_CPU.sh and wCaseMoorings3D_win64_CPU.bat it works under windows unlike on Linux the same issue appears
> ![Untitled](https://user-images.githubusercontent.com/63708484/84897356-1b7a0100-b0ae-11ea-878b-266b05e8e565.png)
> regards Grigor


 Dear Mr Grigor
   I am very interested in the research about how to couple DualSPHysics with MoorDyn.   And l tried to finish the work by myself. To date, I have completed the work on the combining DualSPHysics and MoorDyn DLL. According to the post processing results, It can be seen clearly that the motion of floating body can be limited indeed. But I don’t know how to visualize the mooring lines. Could you give me DualSPHysics5.0 Beta version please? And I just want to figure out how to visualize the moorling lines.
 Thank you very much!
Best regards!
