### ISSUE TITLE
Compiling over Supercomputer

### ISSUE THREAD

**Issue by neelshah0034** [DualSPHysics/DualSPHysics#54]
Hello Team,
My name is Neel Shah,
I am working on DualSPHyiscs, and trying to compiling the Makefile. 
Initially I was facing with "FLT_MAX?" error, but recently I was able to eliminate that error by defining the "#define FLT_MAX 1E+37".
But I am facing some error generated while compiling like:- "DBL_MAX?" and further more (1).
I tried to define DBL_MAX using "#define DBL_MAX 1E+37", but it generated different error (2)
Could you please help me out to compile the code further?
Thank you
PFA:-
1. I have attached the SS for the generated Errors.
[1](https://user-images.githubusercontent.com/55549421/86025775-9b805f00-b9fc-11ea-915f-a88145a3069e.PNG)
2. SS of error generated after defining DBL_MAX.
[2](https://user-images.githubusercontent.com/55549421/86026021-eb5f2600-b9fc-11ea-88b3-d45d57b2b4f3.PNG)

I have tried to copy the images but I don't know why it is not showing up. 
If possible, please let me know the email so that I can email you the Makefile as well as the ScreenShots.

Thank you.

**Comment by jmdalonso** [comment]
Hi,

You should include the libaries with FLT_MAX and DBL_MAX.
"#include <cfloat>" should solve the problem.

Best regards

**Comment by neelshah0034** [comment]
Hi,
I really appreciate your time and effort regarding the reply.
I tried to include the "#include FLT_MAX" and "#include DB:L_MAX"
statements. However, some fatal error is generated.
PFA:-
1. SS of the error.
[image: image.png]

Regards

Neel Shah

MS Aerospace Engineering ERAU

**Comment by neelshah0034** [comment]
the library `#include <cfloat>` is already included in "Function.cpp" file.

Thank you

**Comment by neelshah0034** [comment]
Hello Dominguez,

I have tried the way you suggested to me i.e. by changing each and every
file and separately defining the "DBL_MAX" and "FLT_MAX" values.
And it was a great SUCCESS.
So, I have changed 10-15 files and separately define the double and float
max values in each file. After doing that it successfully compiled.

Now I want to know Is there any way that we can just change 1 file (I mean
by changing Makefile or any other file) so that we don't have to change
every file for defining these values?

Waiting for your prompt reply
Thank you for your cooperation.

Regards

Neel Shah

MS Aerospace Engineering ERAU

**Comment by zlotny** [comment]
Hi there, you could add the definitions to the CCFLAGS Makefile variable, like this:

`CCFLAGS := $(CCFLAGS) -I./ -I$(DIRTOOLKIT)/include -DDBL_MAX=value -DFLT_MAX=othervalue`

as seen on [the GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html)

Hope that helps!

**Comment by neelshah0034** [comment]
Hii Vieira,

The code successfully worked after the command. Thank you for helping me
out. I really appreciate your time and effort.

Thank you

Regards

Neel Shah

MS Aerospace Engineering ERAU
