### ISSUE TITLE
RTX 2080Ti (Compute Capability 7.5)

### ISSUE THREAD

**Issue by MoBork** [DualSPHysics/DualSPHysics#57]
I'd like to run DualSPHysics on RTX 2080Ti x4 (Compute Capability 7.5)
Shall I just add a line (GENCODE:=$(GENCODE) -gencode=arch=compute_75,code=\"sm_75,compute_75\") in the makefile and recompile?

**Comment by DualSPHysics** [comment]
Executables compiled for previous Compute Capability (CC) works fine on RTX2080Ti gpu. I think CC 7.5 is not available using CUDA 9.2. You need to use a higher version of CUDA.

**Comment by MoBork** [comment]
Thank you so much for your reply
