### ISSUE TITLE
[feature request] Measuretool: customize mask value for intermittent regions

### ISSUE THREAD

**Issue by sph-tudelft-nl** [DualSPHysics/DualSPHysics#64]
I am using MeasureTool v5.0.050 (26-02-2020) and have placed a measuring point at a height in the wave range. So this is occupied by fluid particle intermittently. Talking of the forward velocity as an example, I see zeros when there are no fluid particles. But zero is a physically meaningful value for velocity, although of course precisely 0 is quite unlikely (except perhaps at the initial conditions) and can be caught. A possibility to customize the values for masking arrays, like -999 or NaN, would be useful. I haven't spotted it in the help document. Hence this feature request.

**Comment by alexbexe** [comment]
-kcdummy:<float>

1) WIKI in https://github.com/DualSPHysics/DualSPHysics/wiki/5.-Running-DualSPHysics#563-analysis-of-numerical-measurements--measuretool-

The interpolation is computed using the Wendland kernel. Kernel correction is also applied when the summation of the kernel values around the position is higher than a value (-kclimit:) defining a dummy value if the correction is not applied (-kcdummy:). 

2) MeasureTool_Help.o in DualSPHysics_v5.0\doc\help

  -kclimit:<float>    Defines the minimum value of sum_wab_vol to apply the Kernel Correction (default value = 0.5)

  -kcdummy:<float>    Defines the dummy value for the interpolated quantity if Kernel Correction is not applied (default value = 0)

  -kcusedummy:<0/1>   Defines whether or not to use the dummy value (default value = 1)

**Comment by sph-tudelft-nl** [comment]
Received with thanks. The formulations in both sources do not make it immediately clear that measure points with an empty kernel (absence of water) fall in the case covered by the keyword `-kcdummy`. A short description of what 'kernel correction' is may help future readers there. The feature is present, the feature request is closed.
