### ISSUE TITLE
Trouble with building: gethostname function

### ISSUE THREAD

**Issue by NaimSantos** [DualSPHysics/DualSPHysics#68]
While trying to build using the Makecpu file (for Windows, and only the CPU version since I don't have a CUDA compatible device) I ran into an error (see picture 2) with the **gethostname** function, where the building process stops:
![image](https://user-images.githubusercontent.com/26061438/97081381-83020900-15d8-11eb-9e8d-bd4cb457c38b.png)

![image](https://user-images.githubusercontent.com/26061438/97081397-9614d900-15d8-11eb-880b-7530fe4bd604.png)

I also attach the piece of code where the function is called:

```
void JSphCpu::ConfigRunMode(const JSphCfgRun *cfg,std::string preinfo){
  #ifndef WIN32
    const int len=128; char hname[len];
    gethostname(hname,len);
    preinfo=preinfo+(!preinfo.empty()? ", ": "")+"HostName:"+hname;
  #endif
  Hardware="Cpu";
  if(OmpThreads==1)RunMode="Single core";
  else RunMode=string("OpenMP(Threads:")+fun::IntStr(OmpThreads)+")";
  if(!preinfo.empty())RunMode=preinfo+" - "+RunMode;
  if(Stable)RunMode=string("Stable - ")+RunMode;
  RunMode=string("Pos-Double - ")+RunMode;
  Log->Print(" ");
  Log->Print(fun::VarStr("RunMode",RunMode));
  Log->Print(" ");
}
```

Does anyone know what is causing it and/or how to solve it so I can build the project?
Let me know if more details are required.

**Comment by jmdalonso** [comment]
gethostnamde function should be defined in unistd.h for UNIX systems, but if you have any problems with that function you can delete it. It is only used to display the host name.

Best regards

**Comment by NaimSantos** [comment]
That did the job, indeed. I noticed it a earlier too, when the Linux version could be built just fine. Thank you for replying.
