### ISSUE TITLE
Shifting correction

### ISSUE THREAD

**Issue by Wuxizhi2021** [DualSPHysics/DualSPHysics#71]
Hello!
Divergence of a particle position proposed by [Lee et al., 2008] reads
![1](https://user-images.githubusercontent.com/50138854/99182660-22965f80-2771-11eb-9ec2-e351ee4896df.PNG)
But  in the code，the position divergence is calculated like this
![2](https://user-images.githubusercontent.com/50138854/99183082-5aeb6d00-2774-11eb-92d6-643f56f6103c.PNG)
To my understanding the code should be changed to
![3](https://user-images.githubusercontent.com/50138854/99183200-0b597100-2775-11eb-8a78-20face7e91df.PNG)

Kind regards

**Comment by athmokos** [comment]
Hello,

the equation in Lee et al. is incorrect.
Based on the standard SPH divergence operator, the equation should be

![equation_divergence](https://user-images.githubusercontent.com/34512868/99576924-e82ffb00-29da-11eb-8255-5de77c53b591.png)

DualSPHysics uses r_i-r_j necessitating the use of a minus in this equation.

Best regards,
Athanasios Mokos

**Comment by liuchenhui0102** [comment]
I see, thank you very much.

**Comment by liuchenhui0102** [comment]
I see, thank you very much.
