### ISSUE TITLE
Inlet/outlet boundary condition

### ISSUE THREAD

**Issue by cvdr888** [DualSPHysics/DualSPHysics#79]
Hi, 

In the past version 4.4 of DualSPHysics, I've used the open boundary condition imposing the water surface and flow velocity from external files.
Meanwhile, I've updated to last version 5. In the xml in/out file provided in xml_format folder, the referred options (external file for hydrodynamic quantities) are still defined. However, when I try to run the model I get the following message : 

*** Exception (JSphInOut::LoadXmlInit) at ..\source\JSphInOut.cpp:132
Text: Inlet/outlet: <userefilling> is not supported by current inlet/outlet version.
File: TestInlet3D_out/TestInlet3D.xml(row:101)

Here's the xml file (converted to word format, sorry!): [github4help.docx]https://github.com/DualSPHysics/DualSPHysics/files/6049390/github4help.docx)
Any suggestion?

 Many thanks in advance,
CR.

**Comment by imestevez** [comment]
Hello, 

The option <**userefilling**> is not allowed in current version of DualSPHysics. You can download the latest version from [https://dual.sphysics.org/index.php/downloads/](https://dual.sphysics.org/index.php/downloads/) and check the options for  Inlet/outlet in **doc/xml_format/_FmtXML_InOut.xml** and in **doc/guides/XML_GUIDE_INLETOUTLET.pdf**.

Regards

**Comment by cvdr888** [comment]
Thank you! I will. 

Success, 
Cláudia.

**Comment by cvdr888** [comment]
Hello (again), 
Have an issue loading the xml file. Idk if it is related to the xml, the version of DualSPHysics (updated to DualSPHysics_v5.0.3), or any  noob-derived misconception.  I am sending the xml and bat files for suggestions. Please just let me know if you need any additional information.  Thank you for the support! 
Cláudia 

[wTest_Inlet_win64_GPU.zip](https://github.com/DualSPHysics/DualSPHysics/files/6069359/wTest_Inlet_win64_GPU.zip)


Error: 

GenCase v5.0.229 (29-01-2021)
===============================
LoadDsphConfig> .../bin/windows/DsphConfig.xml
OmpThreads: 12

[LoadXMLInit]

*** Exception (JXml::LoadFile) at ..\Source\JXml.cpp:900
Text: Cannot load the xml file: Error reading Attributes. (row:122 col:103)
File: Test_Inlet_Def.xml


Finished execution (code=1).

Execution aborted.
Press any key to continue . . .

**Comment by imestevez** [comment]
Hello, that Exception was thrown because an underscore is missing in the attribute **units_comment** of the **zbottom** option (row:122).
Regards
