### ISSUE TITLE
How to use openMP for parallelism

### ISSUE THREAD

**Issue by Liang-guo-du** [DualSPHysics/DualSPHysics#97]
Hello!
      I'm new to Dualsphysics, and I want to use CPU for parallel computing, but how do I set up openMP?I have found many literatures, but none of them explain how to use openMP. Who can help me? Thank you!!

**Comment by jmdalonso** [comment]
When DualSPHysics runs on CPU by default it uses all available CPU cores. This can be changed using the execution parameter -ompthreads.

    -ompthreads:<int>  Only for CPU execution, indicates the number of threads
                   by host for parallel execution, this takes the number of 
                   cores of the device by default (or using zero value)

**Comment by Liang-guo-du** [comment]
> 当 DualSPPhysics 默认在 CPU 上运行时，它会使用所有可用的 CPU 内核。这可以使用执行参数 -ompthreads 进行更改。
> 
![1](https://user-images.githubusercontent.com/83148560/143517283-d07235cb-cd43-4c40-b224-0a866b7e3c87.PNG)
![2](https://user-images.githubusercontent.com/83148560/143517286-94e3d641-946f-4586-a0b2-a91e627a64e8.PNG)

> ```
> -ompthreads:<int>  Only for CPU execution, indicates the number of threads
>                by host for parallel execution, this takes the number of 
>                cores of the device by default (or using zero value)
> ```
OH,thank you!!
After I run a case, the "case_.out" file shows "OmpThreads: 16", but the "run.out" file shows "Threads by host for parallel execution: 64". Does this mean that the program is called? 64 threads? Why does this happen?

**Comment by imestevez** [comment]
Hello. It is already working with OpenMP. GenCase and DualSPHysics will take as many threads as CPU cores by default. In that case, GenCase is running with different number of threads than DualSPHysics because you should define -ompthreads:X to launch both tools with the same number of OpenMP threads.
