### ISSUE TITLE
About the parallel problem of using chrono

### ISSUE THREAD

**Issue by Liang-guo-du** [DualSPHysics/DualSPHysics#99]
Hello!
I recently tried to use the chrono function to do some research, but found that only one thread was called when using the chrono function. In the "run.out" file, I found "Threads by host for parallel execution in Chrono:1", which means that only one thread can be used. Thread to calculate. How should I modify it to make it calculate faster?
![3](https://user-images.githubusercontent.com/83148560/143518968-689b97a5-6265-47fd-b352-5dc614b7fe41.PNG)

Thank you!

Regards.

**Comment by imestevez** [comment]
Hello! Chrono isn't able to work with parallel execution in this coupling yet. Therefore, only 1 thread can be used.
